### PR TITLE
New Polish translation

### PR DESCRIPTION
**Pull request by GregoreoNevrati**
More comments in the file. I have tried just to modify old file but the system did not let me, so I removed it and uploaded new one.

### CODE REVIEW

**Comment by ginggs** [comment]
Thanks for the pull request!  Deleting and the uploading the file makes it very hard to review the changes.  Would you please try squashing the commits and pushing again?

**Comment by GregoreoNevrati** [comment]
Hello,
I was unfortunately unable to do so, because the confirmation button was
not active whatever I would do, or I simply can't do it properly. I can
obviously try again.
At the same time, when I uploaded a new file, all changes were neatly shown
and it is strange by my side that you don't see it.
I am very grateful for your response, yours faithfully,

Grzegorz Nowiak

czw., 26 wrz 2019, 15:28 użytkownik Graham Inggs <notifications@github.com>
napisał:

**Comment by ginggs** [comment]
Don't worry too much if you are unable to squash the commits.  I can do it on my side later.

**Comment by GregoreoNevrati** [comment]
I was talking about my first input when I couldn't edit this file. About
squashing - I don't have this file on hand and don't want to delete it
before tomorrow.

Grzegorz Nowiak

czw., 26 wrz 2019, 15:48 użytkownik Graham Inggs <notifications@github.com>
napisał:

**Pull request closed without merging**
